language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - 5.6

matrix:
    allow_failures:
        - php:
          - hhvm
          - 5.6
          
install: composer install
script: phpunit --configuration tests/FullTests.xml
