language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
    allow_failures:
        - php:
          - hhvm
          
install: composer install
script: phpunit --configuration tests/FullTests.xml
